-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 18:33:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema week8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema week8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `week8` DEFAULT CHARACTER SET utf8 ;
USE `week8` ;

-- -----------------------------------------------------
-- Table `week8`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`supplier` (
  `sname` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`sname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`project` (
  `proj_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`proj_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`part` (
  `Part_no` INT NOT NULL,
  PRIMARY KEY (`Part_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`bank` (
  `code` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `addr` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`bank_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`bank_branch` (
  `addr` VARCHAR(45) NULL,
  `branch_no` INT NOT NULL,
  `bank_code` INT NOT NULL,
  PRIMARY KEY (`bank_code`, `branch_no`),
  INDEX `fk_bank_branch_bank1_idx` (`bank_code` ASC) VISIBLE,
  CONSTRAINT `fk_bank_branch_bank1`
    FOREIGN KEY (`bank_code`)
    REFERENCES `week8`.`bank` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`account` (
  `acct_no` INT NOT NULL,
  `balance` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `bank_branch_bank_code` INT NOT NULL,
  PRIMARY KEY (`acct_no`),
  INDEX `fk_account_bank_branch1_idx` (`bank_branch_bank_code` ASC) VISIBLE,
  CONSTRAINT `fk_account_bank_branch1`
    FOREIGN KEY (`bank_branch_bank_code`)
    REFERENCES `week8`.`bank_branch` (`bank_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`customer` (
  `Ssn` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `addr` VARCHAR(45) NULL,
  PRIMARY KEY (`Ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`loan` (
  `loan_no` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `bank_branch_bank_code` INT NOT NULL,
  PRIMARY KEY (`loan_no`),
  INDEX `fk_loan_bank_branch1_idx` (`bank_branch_bank_code` ASC) VISIBLE,
  CONSTRAINT `fk_loan_bank_branch1`
    FOREIGN KEY (`bank_branch_bank_code`)
    REFERENCES `week8`.`bank_branch` (`branch_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`A_C`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`A_C` (
  `account_acct_no` INT NOT NULL,
  `customer_Ssn` INT NOT NULL,
  INDEX `fk_account_has_customer_customer1_idx` (`customer_Ssn` ASC) VISIBLE,
  INDEX `fk_account_has_customer_account1_idx` (`account_acct_no` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_customer_account1`
    FOREIGN KEY (`account_acct_no`)
    REFERENCES `week8`.`account` (`acct_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_customer_customer1`
    FOREIGN KEY (`customer_Ssn`)
    REFERENCES `week8`.`customer` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`L_C`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`L_C` (
  `loan_loan_no` INT NOT NULL,
  `customer_Ssn` INT NOT NULL,
  INDEX `fk_loan_has_customer_customer1_idx` (`customer_Ssn` ASC) VISIBLE,
  INDEX `fk_loan_has_customer_loan1_idx` (`loan_loan_no` ASC) VISIBLE,
  CONSTRAINT `fk_loan_has_customer_loan1`
    FOREIGN KEY (`loan_loan_no`)
    REFERENCES `week8`.`loan` (`loan_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_has_customer_customer1`
    FOREIGN KEY (`customer_Ssn`)
    REFERENCES `week8`.`customer` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`supplier_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`supplier_has_project` (
  `supplier_sname` VARCHAR(9) NOT NULL,
  `project_proj_name` VARCHAR(20) NOT NULL,
  INDEX `fk_supplier_has_project_project1_idx` (`project_proj_name` ASC) VISIBLE,
  INDEX `fk_supplier_has_project_supplier1_idx` (`supplier_sname` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_has_project_supplier1`
    FOREIGN KEY (`supplier_sname`)
    REFERENCES `week8`.`supplier` (`sname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_project_project1`
    FOREIGN KEY (`project_proj_name`)
    REFERENCES `week8`.`project` (`proj_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`can_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`can_supply` (
  `supplier_sname` VARCHAR(9) NOT NULL,
  `part_Part_no` INT NOT NULL,
  INDEX `fk_supplier_has_part_part1_idx` (`part_Part_no` ASC) VISIBLE,
  INDEX `fk_supplier_has_part_supplier1_idx` (`supplier_sname` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_has_part_supplier1`
    FOREIGN KEY (`supplier_sname`)
    REFERENCES `week8`.`supplier` (`sname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_has_part_part1`
    FOREIGN KEY (`part_Part_no`)
    REFERENCES `week8`.`part` (`Part_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `week8`.`uses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `week8`.`uses` (
  `project_proj_name` VARCHAR(20) NOT NULL,
  `part_Part_no` INT NOT NULL,
  INDEX `fk_project_has_part_part1_idx` (`part_Part_no` ASC) VISIBLE,
  INDEX `fk_project_has_part_project1_idx` (`project_proj_name` ASC) VISIBLE,
  CONSTRAINT `fk_project_has_part_project1`
    FOREIGN KEY (`project_proj_name`)
    REFERENCES `week8`.`project` (`proj_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_part_part1`
    FOREIGN KEY (`part_Part_no`)
    REFERENCES `week8`.`part` (`Part_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
